### ISSUE TITLE
Unable to find method ''org.gradle.api.tasks.TaskOutputs org.gradle.api.tasks.TaskOutputs.files(java.lang.Object[])''.

### ISSUE THREAD

**Issue by Folko85** [d10xa/gradle-allure-plugin#14]
Пытаюсь сейчас связать geb с селеноидом. В официальном аллюровском плагине про geb ничего не нашёл, а здесь уже на стадии добавления в градле такая ошибка. Нагуглил, что нужна другая версия градла, но может есть другое решение?

**Comment by Folko85** [comment]
Хм. Увидел сейчас форк, где эта проблема исправлена https://github.com/iherasymenko/gradle-allure-plugin Жаль конечно, что всё застыло и не обновляется. Ну да ладно.

**Comment by d10xa** [comment]
@Folko85
Allure 1 прекратил обновляться в мае 2017. Почему ты не переходишь на версию 2? Теперь есть [официальный плагин](https://github.com/allure-framework/allure-gradle`) для allure2, нужно брать его.
Geb это не то, ради чего стоит продолжать использовать весь плагин. 
Всё что нужно для geb, это добавить зависимость https://github.com/d10xa/allure-spock-geb
Попробуй  так: https://github.com/d10xa/gradle-allure-plugin/issues/13#issuecomment-463787000
Вот эта [ветка с исправлением](https://github.com/d10xa/allure-spock-geb/compare/allure-2), если ты скажешь что она работает для тебя - смержу в мастер.
Я старался, фиксил, но в итоге мне ни кто не ответил и я забил.
Про форк iherasymenko я не знал. В таких случаях обычно пулл реквесты открывают (там фикс на 2 строчки), а он в итоге решил от своего имени зарелизить. Ну пофиг, лицензия позволяет.
Если захочешь что то изменить, оформляй пулл реквест, я смержу.

**Comment by Folko85** [comment]
Я в этом деле вообще новичок и allure только пробую. Поэтому возможно что-то не так делаю. Мне действительно нужно как-то с гебом интегрироваться, вот я и полез сюда исключительно ради него. Рад, что проект не заброшен-таки. Скорей всего воспользуюсь методом из комментария (был невнимателен, сразу не заметил). Исправление завтра проверю.
